# Generated by Django 3.1.7 on 2021-02-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20210222_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
